### ISSUE TITLE
Add ability to set expressive font via lg-font-size mixin

### ISSUE THREAD

**Issue by owensgit** [Legal-and-General/canopy#224]
Currently the only way to apply the expressive (Lyon) font is to use the CSS modifier: `lg-font--expressive`. 

We should also add the ability to apply the expressive font when using the `@lg-font-size` mixin, with the default being the productive (Robot) font.

Current mixin:

```
@mixin lg-font-size($size, $modifier: null) {
  font-size: var(--text-fs-#{$size}-size);
  line-height: var(--text-fs-#{$size}-line-height);

  @if $modifier {
    font-weight: var(--text-fs-#{$size}-weight--#{$modifier});
  } @else {
    font-weight: var(--text-fs-#{$size}-weight);
  }
}
```

Possible approach could be to include a third parameter: `@mixin lg-font-size($size, $modifier: null, $fontType: 'productive')`.

**Comment by AlenNS** [comment]
@owensgit I would suggest setting type parameter as null, since we would like to avoid overriding font family from another class if no class provided to size mixin.

Example with **type** parameter as _null_:
![image](https://user-images.githubusercontent.com/19712379/118502584-8276be80-b732-11eb-8680-67bdb8e16841.png)
Example with **type** parameter default value as _productive_:
![image](https://user-images.githubusercontent.com/19712379/118502600-84d91880-b732-11eb-9f06-42973a39f150.png)

We can extend the mixin later if needed, but for now we would check if the parameter value is _expressive_ to set **Lyon** font or _productive_ to set **Roboto** font, but we would not set font-family and prevent overriding the other class property if nothing is provided to the mixin.
