### ISSUE TITLE
Upgrade to storybook 6

### ISSUE THREAD

**Issue by aaronBery** [Legal-and-General/canopy#35]
This was initially flagged in https://github.com/Legal-and-General/canopy/pull/28 which references a handy [migration guide](https://medium.com/storybookjs/storybook-6-migration-guide-200346241bb5) on medium.

There are breaking changes associated with the upgrade and also decisions on best practice to be made e.g. which story format to adopt

**Comment by elenagarrone** [comment]
Also, you will have to consider the dsm storybook npm package. I quickly had a look at this when doing the dependencies upgrades a while ago and it didn't seem that straight forward. It might have changed in the past month 🤞

**Comment by thatguynamedandy** [comment]
I'm not happy with that DSM package and the amount of dependencies it has, which potentially hold us back on updates. A new version did get published two weeks ago, but from what I can see the release notes aren't published.
https://www.npmjs.com/package/@invisionapp/dsm-storybook

I wouldn't be opposed to looking at alternatives, to me it would seem simpler if we just iframed the storybook page into the DSM.

**Comment by thatguynamedandy** [comment]
I had a few goes at playing around with this recently, there are some pretty big changes. 

I made better progress by removing the existing `.storybook' directory and then just running a single story. The `Alert` component was a good candidate for simplicity. From what I could see though, content projection prevents us from using the simplest approach.

I think Storybook 6 might reduce lots of the documentation we need to do. We could consider removing the html only support from the docs.

**Comment by thatguynamedandy** [comment]
@paul-request what were your findings in the end? did you have any further ideas on how to tackle it?

**Comment by paul-request** [comment]
So I didn't get as far as I would have liked, but I have managed to upgrade and get it running with an Alert component.

These are the main things to take away I think:

- Automatic documentation is achieved by using Compodoc internally, which has turned out to be massively disappointing. It doesn't do much more than add descriptions. So actually we would still be required to add documentation for local variables and functions manually.
- Compodoc also adds private variables into the docs and controls, so these would have to be ignored explicitly using a comment (not ideal).
- Knobs is replaced by Controls, which has a new API to use. Seems fine, but there is an outstanding bug where changing the controls in the docs tab doesn't update the example.  (https://github.com/storybookjs/storybook/issues/11908)

Still todo:
- There is a new feature called [DocsPage](https://storybook.js.org/docs/angular/writing-docs/introduction), which I need to look into that further. At first glance, it looks like we can just use it by creating a markdown file, instead of exporting strings of markdown from ts.
- Look at a more complex component with variants and see if there are other things that may not work without further configuration/changes.
- Investigate DSM integration.
