### ISSUE TITLE
Issue with svgo dependency

### ISSUE THREAD

**Issue by AlexandruHoisan** [Legal-and-General/canopy#385]
When running the command ``npm run optimise:svgs`` it would break with the following error:
![Screenshot 2021-05-26 at 14 51 57](https://user-images.githubusercontent.com/68600084/119682083-44bd1880-be4b-11eb-934f-44d5861eef21.png)

This was blocking the actual commit, as when we run ``npm run commit`` it will also breack at the ``npm run build:icons`` step.

Posible solutions:
*change the svgo dependencie from ``2.3.0`` back to version ``1.3.0`` . This seems to work as expected.

**Comment by owensgit** [comment]
This is because **svgo** 2.3.0 has changed the way you setup the config.

Instead of a JSON file (as is currently), it's now a JS module. 

Docs: https://github.com/svg/svgo#configuration

This is quite easy to do, but one hurdle is that we also run **svg-to-ts**, which accepts an **svgo** config - however it still runs the previous version and expects a JSON config file.

I've raised an issue with **svg-to-ts**: https://github.com/kreuzerk/svg-to-ts/issues/127

I think we have two options:

1. Wait until **svg-to-ts** is updated and update both at the same time
2. Create the new config files now and update **svgo**, but leave the old config files in there for **svg-to-ts** until it has been updated.

**Comment by elenagarrone** [comment]
Looks like `svg-to-ts` has been updated: https://github.com/Legal-and-General/canopy/pull/581
