### ISSUE TITLE
Sort code fields are too wide

### ISSUE THREAD

**Issue by aaronBery** [Legal-and-General/canopy#483]
Some work was recently done to fix spacing between sort code fields on https://github.com/Legal-and-General/canopy/pull/464 however one side effect is that it has widened the field.

Before (55px wide)

![Screenshot 2021-07-19 at 10 33 42](https://user-images.githubusercontent.com/7768665/126138573-42653c5d-bd21-4518-8c62-541c5d7edf8a.png)

After (58px wide)
![Screenshot 2021-07-19 at 10 29 29](https://user-images.githubusercontent.com/7768665/126138647-e677da97-65e7-44d6-b8e4-4ca864e8b358.png)

Tests performed on MS Edge on a Macbook Pro

**Comment by aaronBery** [comment]
It may be worth investigating whether a similar issue now occurs on the date field which was also worked on as part of this work

**Comment by elenagarrone** [comment]
Would we consider this an issue? one for @alexcanning I guess?

**Comment by Hopkinsa** [comment]
Hi,  Just opened a PR for this.  Looking at the scss files the size of the sort code input fields were originally meant to be about 60px. However, through padding and other css it ended up being about 55px. The update from #464 forced the input to resize correctly, which has led to this discrepancy. 
The width for the individual sort code input boxes has now been set to 55px (3.4375rem), rather than the original 60px (3.75rem).

**Comment by aaronBery** [comment]
> Would we consider this an issue? one for @alexcanning I guess?

I consulted Michelle who considered it an issue and one that we needed to resolve before upgrading our projects canopy version

**Comment by elenagarrone** [comment]
Thanks for checking @aaronBery 👍  PR merged now 👍
